name: Arduino Library CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check out branch main
        uses: actions/checkout@v4
      
      - uses: actions/checkout@v4
        with:
           repository: cyijun/ci-arduino
           path: ci
  
      - name: main:pre-install
        run: bash ci/actions_install.sh
  
      - name: main:build test
        run: python3 ci/build_platform.py esp32

      - name: Check out branch next
        uses: actions/checkout@v4
        with:
          ref: next

      - uses: actions/checkout@v4
        with:
          repository: adafruit/ci-arduino
          path: ci
            
      - name: next:pre-install
        run: bash ci/actions_install.sh
    
      - name: next:build test
        run: python3 ci/build_platform.py esp32