name: Arduino Library CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
           repository: cyijun/ci-arduino
           path: ci
  
      - name: pre-install
        run: bash ci/actions_install.sh
  
      - name: test platforms
        run: python3 ci/build_platform.py esp32
