name: Arduino Library CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check out branch main
        uses: actions/checkout@v4
      
      - uses: actions/checkout@v4
        with:
           repository: cyijun/ci-arduino
           path: ci
  
      - name: pre-install
        run: bash ci/actions_install.sh
  
      - name: build test
        run: python3 ci/build_platform.py esp32
