name: ESP-IDF CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_esp_idf_example:
    name: Build CppEspIdf example with ESP-IDF v${{ matrix.idf_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_version: ['v4.4.6', 'v5.3']

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/app

      - name: Build with ESP-IDF ${{ matrix.idf_version }}
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_version }}
          target: esp32
          path: app/examples/CppEspIdf
          command: |
            apt-get update && apt-get install -y python3-venv
            idf.py build